version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      args:
        - DEV=true
    init: true
    restart: no
    env_file:
      # - ./env/web.env
      - ./env/mongo.env
      - ./env/web.env
      - ./env/ingest.env
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy 
  search-worker-1:
    build:
      context: .
      dockerfile: docker/search.Dockerfile
    init: true
    restart: no
    stop_grace_period: 30s
    profiles: ["search"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    environment:
      - WORKER_ID=1
    depends_on:
      mongo:
        condition: service_healthy

  search-worker-2:
    build:
      context: .
      dockerfile: docker/search.Dockerfile
    init: true
    restart: no
    stop_grace_period: 30s
    profiles: ["search"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    environment:
      - WORKER_ID=2
    depends_on:
      mongo:
        condition: service_healthy

  readme-worker-1:
    build:
      context: .
      dockerfile: docker/readme.Dockerfile
    init: true
    restart: no
    stop_grace_period: 30s
    profiles: ["readme"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    environment:
      - WORKER_ID=1
      - TOTAL_WORKERS=2
    volumes:
      - ./src/ingest:/src/ingest
    depends_on:
      mongo:
        condition: service_healthy
  readme-worker-2:
    build:
      context: .
      dockerfile: docker/readme.Dockerfile
    init: true
    restart: no
    stop_grace_period: 30s
    profiles: ["readme"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    environment:
      - WORKER_ID=2
      - TOTAL_WORKERS=2
    volumes:
      - ./src/ingest:/src/ingest
    depends_on:
      mongo:
        condition: service_healthy

  readme-classify-worker:
    build:
      context: .
      dockerfile: docker/classify.Dockerfile
    init: true
    restart: no
    stop_grace_period: 30s
    profiles: ["readme-classify"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    environment:
      - WORKER_ID=1
    volumes:
      - ./src/ingest:/src/ingest
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    expose:
      - "27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-dev-data:
