version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      args:
        - DEV=true
    init: true
    container_name: web-service
    restart: no
    env_file:
      # - ./env/web.env
      - ./env/mongo.env
      - ./env/web.env
      - ./env/ingest.env
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy 
  ingest-worker:
    build:
      context: .
      dockerfile: docker/ingest.Dockerfile
    container_name: ingest-worker-1
    restart: unless-stopped
    profiles: ["ingest"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    depends_on:
      mongo:
        condition: service_healthy

  # Worker 병렬 처리 예시 (필요 시 주석 해제)
  # ingest-worker-2:
  #   build:
  #     context: .
  #     dockerfile: docker/ingest.Dockerfile
  #   container_name: ingest-worker-2
  #   restart: unless-stopped
  #   profiles: ["ingest"]
  #   env_file:
  #     - ./env/ingest.env
  #     - ./env/mongo.env
  #   depends_on:
  #     mongo:
  #       condition: service_healthy

  enrichment-worker:
    build:
      context: .
      dockerfile: docker/enrichment.Dockerfile
    container_name: enrichment-worker-1
    restart: unless-stopped
    profiles: ["enrichment"]
    env_file:
      - ./env/ingest.env
      - ./env/mongo.env
    depends_on:
      mongo:
        condition: service_healthy

  # README Enrichment Worker 병렬 처리 (필요 시 주석 해제)
  # enrichment-worker-2:
  #   build:
  #     context: .
  #     dockerfile: docker/enrichment.Dockerfile
  #   container_name: enrichment-worker-2
  #   restart: unless-stopped
  #   profiles: ["enrichment"]
  #   env_file:
  #     - ./env/ingest.env
  #     - ./env/mongo.env
  #   depends_on:
  #     mongo:
  #       condition: service_healthy


  mongo:
    image: mongo:7
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    expose:
      - "27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-dev-data:
